FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir kafka-python jsonschema pyyaml python-dotenv

COPY src/ src/
COPY configs/ configs/

CMD ["python", "-m", "src.main", "--mode", "producer"]
